@echo off
echo Starting Air Quality AI Agent Backend...
cd /d "e:\Agent\ai-air-quality-agent\backend"
echo Installing dependencies...
pip install fastapi uvicorn python-dotenv pandas openai
echo Starting server on http://localhost:8000...
python -m uvicorn main:app --host 0.0.0.0 --port 8000 --reload
pause
